services:
  - type: web
    name: finstream-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: MODEL_NAME
        value: hitenvk22/FinStream-Sentiment
      - key: MODEL_BACKEND
        value: rule_based
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: HF_TOKEN
        sync: false

  - type: web
    name: finstream-frontend
    runtime: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: FinStream
      - key: BACKEND_API_URL
        fromService:
          name: finstream-backend
          type: web
          property: hostport
